### ISSUE TITLE
Visas required

### ISSUE THREAD

**Issue by 01450900** [anthonygoslar/LMS-Support#147]
Hello, 
I've got a few students who went from Confirmed to CURRENT Today.  On the Dashboard - incoming - This Monday - I can see that ID doc required  pic(1) so I think why has it gone to CURRENT then, but when I check, it has an ID doc (pic 2)

Others are:  HSOR35554), ERIC33518), AALG36154), AALA36534)
![1](https://user-images.githubusercontent.com/77271198/119349001-e3a41200-bc9d-11eb-9060-ea548abdb20f.JPG)
![pic 2](https://user-images.githubusercontent.com/77271198/119349022-ea328980-bc9d-11eb-8a7e-717773935767.JPG)

**Comment by anthonygoslar** [comment]
Hi. It was the missing expiry date on the ID. I put it in there to force administrators to actually check if its valid rather than just taking a photo and uploading it. I've added expiry dates to the IDs and they're all shown up as green. In the backend I check ID expiry dates, as you can have a case where a VISA is not required but a valid ID is required.
